name: global_charity_analytics
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.11.2
  - numpy=1.24.3
  - pandas=1.5.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - statsmodels=0.13.5
  - scikit-learn=1.2.2
  - requests=2.31.0
